### ISSUE TITLE
Allocating 문제

### ISSUE THREAD

**Issue by happy-jihye** [Naver-AI-Hackathon/SNU-Advanced-GANs#1]
안녕하세요. 인공지능 특강 수업을 듣고있는 백지혜입니다.

학습을 하던 중 실수로 stop을 했는데, 계속해서 "Allocating!"이 뜨고 있는 상태입니다.
이를 강제로 꺼주실 수 있을까요 ?

snu-27/cifar10/4
입니다! 감사합니다.

**Comment by bluebrush** [comment]
@happy-jihye 님, snu-27/cifar10/4 은 삭제된 것을 확인됩니다. 
이 후, 비슷한 경우에는 `nsml rm -f [session-ID]` 명령을 실행하시면 도움이 될 것 같습니다. 
예) `nsml rm -f  snu-27/cifar10/4`
