### ISSUE TITLE
Multiple gpus

### ISSUE THREAD

**Issue by deploy-soon** [Naver-AI-Hackathon/SNU-Advanced-GANs#10]
안녕하세요
지난 글에서 한 세션에 하나의 gpu만 사용하다고 본 것 같은데 확실하지 않아서
실제로 한 세션에서 여러 gpu를 병렬처리하기 어려운지 궁금합니다.
실습 시간에 간접적으로 병렬처리가 가능하다고 얼핏 들은 것 같기도 합니다..

**Comment by bluebrush** [comment]
@deploy-soon 님, 본인 쿼터가 허용된다면, 최대 4GPUs 까지 단일 세션에서 실행가능한 상태입니다. 
nsml run -g 4 ... 형식입니다.

**Comment by deploy-soon** [comment]
제가 착각했네요ㅜ 감사합니다
