### ISSUE TITLE
multiple datasets

### ISSUE THREAD

**Issue by halo8218** [Naver-AI-Hackathon/SNU-Advanced-GANs#3]
안녕하세요, 

nsml run -d 할 때  한 가지 dataset만을 쓰는게 아니라 추가적인 dataset을 가져오기 위해서는 어떠한 방법을 사용해야 하나요?

**Comment by bluebrush** [comment]
안녕하세요. @halo8218 님. 
`nsml run -d dataset-1 -d dataset-2 -d dataset-3 ... `이렇게 실행하시면됩니다.

**Comment by halo8218** [comment]
답변 감사드립니다.
