### ISSUE TITLE
run 예약

### ISSUE THREAD

**Issue by halo8218** [Naver-AI-Hackathon/SNU-Advanced-GANs#4]
안녕하세요,
보통 shell 파일로 python 파일 줄세워 돌리는 것 처럼
nsml run도 세션이 끝나고 사용가능한 cpu, gpu가 생겼을 때 자동으로 돌아가게끔 대기 걸어놓을 수 있는 방법이 있을까요?

**Comment by bluebrush** [comment]
@halo8218 님, 현재 run을 예약하거나 큐잉하는 기능은 제공하고 있지 않습니다.

**Comment by halo8218** [comment]
답변 감사드립니다.
