### ISSUE TITLE
torch.load 관련 오류

### ISSUE THREAD

**Issue by happy-jihye** [Naver-AI-Hackathon/SNU-Advanced-GANs#5]
안녕하세요, 학습을 하던 중 오류가 생겨 질문을 드립니다.

![image](https://user-images.githubusercontent.com/78718131/116029575-962f8780-a694-11eb-91ec-2829ddcb982e.png)

다음과 같이 pretrained된 모델을 push한 후, 이를 load하여 학습을 시켜고 하였는데
pt파일이 load되지 않아서요.. 혹시 이유를 알 수 있을까요?
data path를 살펴보니 다음의 path에 제가 push한 pt파일이 있는 것 같아 
```--ckpt data/stylegan2_pre_ffhq/train```
다음의 명령어를 입력한 후 학습을 하였습니다.

```python
NSML Log start!
Traceback (most recent call last):
  File "generate.py", line 81, in <module>
    checkpoint = torch.load(args.ckpt)
  File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 419, in load
    f = open(f, 'rb')
IsADirectoryError: [Errno 21] Is a directory: 'data/stylegan2_pre_ffhq/train'
User session exited
```

**Comment by bluebrush** [comment]
@happy-jihye , session link 제공 가능하실까요? 또는 세션 ID?

**Comment by happy-jihye** [comment]
답변 감사드립니다!

https://ai.nsml.navercorp.com/terminal/snu-27/stylegan2_pre_ffhq/11
session link입니다. (다른 세션들 모두 동일한 오류가 발생합니다.)

예전에 다른 모델 학습시켰던 걸 보니
경로가 다음과 같이 설정되어있을 때 학습이 됐었는데,
```celeba_image_dir='/data/celeba/train'```

이번 모델은
```--ckpt /data/stylegan2_pre_ffhq/train``` 이렇게 해도 학습이 안되네요ㅠ

**Comment by bluebrush** [comment]
@happy-jihye 님, 
session 내부의 경로 및 파일은 아래와 같이 확인됩니다. 
아래 정보로 확인 가능하실까요?

```
 28064009      0 drwxr-xr-x   3 root     root           19 Apr 25 17:04 /data/stylegan2_pre_ffhq/
608710446      0 drwxr-xr-x   3 root     root           23 Apr 25 17:04 /data/stylegan2_pre_ffhq/train
1101708762      0 drwxr-xr-x   2 root     root           23 Apr 25 17:04 /data/stylegan2_pre_ffhq/train/stylegan2
1101708763 807644 -rw-r--r--   1 root     root     827025138 Apr 25 17:03 /data/stylegan2_pre_ffhq/train/stylegan2/550000.pt
```

**Comment by happy-jihye** [comment]
네:) 확인했습니다.

혹시 data 내부의 경로 및 파일을 확인할 수 있는 명령어도 알려주실 수 있으신가요?
