### ISSUE TITLE
nsml 다운로드 이슈

### ISSUE THREAD

**Issue by happy-jihye** [Naver-AI-Hackathon/SNU-Advanced-GANs#6]
![image](https://user-images.githubusercontent.com/78718131/116884314-91a13b00-ac61-11eb-8b03-698196e57be1.png)

안녕하세요, 학습 시킨 데이터를 다운받으려고 하는데 다운이 안돼서 질문을 드립니다.
내부 경로를 확인해보면 png파일들이 있는 게 확인이 되는데, 
nsml download로도 다운이 안되고,
nsml pull을 통해 세션 폴더 전체를 다운받아봐도 내부에 이미지 파일이 없어서요!

마찬가지로 다른 파일들을 다운받을 때에도 새로 생성된 파일들이 다운로드가 되지 않습니다ㅠ
![image](https://user-images.githubusercontent.com/78718131/116885292-b1852e80-ac62-11eb-8bd3-4f81100c54b5.png)

생성된 결과를 다운 받는 방법이 있을까요?

**Comment by bluebrush** [comment]
@happy-jihye 님, 오류 상태확인 중이었는데요.  2021-05-04T20:35:47+09:00 에 해당 세션 삭제된 것으로 확인됩니다.

**Comment by happy-jihye** [comment]
답변 감사드립니다! 비슷한 세션들이 많아서 삭제를 했네요ㅠ
snu-27/None/20, snu-27/None/22 
이 세션들 모두 같은 오류가 발생해서 이 세션들로 확인하시면 될 것 같습니다! 감사합니다.

**Comment by bluebrush** [comment]
@happy-jihye 님, 사용하신 docker image에 설치된 tar 버전이슈가 있어서 문제가 있었습니다. 
현재, fix되어 정상동작하고 있습니다.

**Comment by happy-jihye** [comment]
해결 되었습니다! 도움주셔서 감사합니다  :)
