### ISSUE TITLE
Illegal instruction 이슈

### ISSUE THREAD

**Issue by nuguziii** [Naver-AI-Hackathon/SNU-Advanced-GANs#8]
안녕하세요,

세션을 실행하는 과정에서 아래와 같은 오류가 발생합니다.
로컬에서는 문제없이 돌아가는 코드인데 혹시 어떤 부분에서 오류가 나는건지 알 수 있을까요?

![image](https://user-images.githubusercontent.com/35167935/119092811-dc84c600-ba49-11eb-8e73-f9d8d1336472.png)

**Comment by bluebrush** [comment]
session ID 알수 있을까요?

**Comment by nuguziii** [comment]
snu-19/LADataset/34 입니다

**Comment by nuguziii** [comment]
버전 문제였던 것 같습니다 해결 되었습니다!
