### ISSUE TITLE
지난 session restart

### ISSUE THREAD

**Issue by happy-jihye** [Naver-AI-Hackathon/SNU-Advanced-GANs#9]
안녕하세요,

학습중에 세션을 중단하였는데 혹시 재시작하는 방법이 있을까요?
중단된 부분부터 학습이 가능한지, 아니면 아예 처음부터 학습을 해야하는건지 궁금합니다 !

**Comment by bluebrush** [comment]
@happy-jihye 님, 두가지 방법이 가능할듯 합니다. 
1.  nsml fork()가 있습니다. 
https://n-clair.github.io/ai-docs/_build/html/ko_KR/contents/session/fork_a_session.html?highlight=fork
2. 기존 세션의 모델 load하기 
3. https://n-clair.github.io/ai-docs/_build/html/ko_KR/contents/load_model.html

**Comment by happy-jihye** [comment]
감사합니다:))
